version: "3.4"

services:
  db:
    image: postgres:11
    restart: always
    ports:
      - "6432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local

networks:
  tabby:
    external: true
