// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Hero struct {
	ID        uuid.UUID
	HeroName  string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Item struct {
	ID        uuid.UUID
	ItemName  string
	Link      sql.NullString
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
